/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CreateWatchlistRouteImport } from './routes/create-watchlist'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AssetTickerRouteImport } from './routes/asset.$ticker'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateWatchlistRoute = CreateWatchlistRouteImport.update({
  id: '/create-watchlist',
  path: '/create-watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetTickerRoute = AssetTickerRouteImport.update({
  id: '/asset/$ticker',
  path: '/asset/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/create-watchlist': typeof CreateWatchlistRoute
  '/lists': typeof ListsRoute
  '/login': typeof LoginRoute
  '/rankings': typeof RankingsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/asset/$ticker': typeof AssetTickerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/create-watchlist': typeof CreateWatchlistRoute
  '/lists': typeof ListsRoute
  '/login': typeof LoginRoute
  '/rankings': typeof RankingsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/asset/$ticker': typeof AssetTickerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/create-watchlist': typeof CreateWatchlistRoute
  '/lists': typeof ListsRoute
  '/login': typeof LoginRoute
  '/rankings': typeof RankingsRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/asset/$ticker': typeof AssetTickerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/create-watchlist'
    | '/lists'
    | '/login'
    | '/rankings'
    | '/register'
    | '/search'
    | '/asset/$ticker'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/create-watchlist'
    | '/lists'
    | '/login'
    | '/rankings'
    | '/register'
    | '/search'
    | '/asset/$ticker'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/create-watchlist'
    | '/lists'
    | '/login'
    | '/rankings'
    | '/register'
    | '/search'
    | '/asset/$ticker'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  CreateWatchlistRoute: typeof CreateWatchlistRoute
  ListsRoute: typeof ListsRoute
  LoginRoute: typeof LoginRoute
  RankingsRoute: typeof RankingsRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  AssetTickerRoute: typeof AssetTickerRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-watchlist': {
      id: '/create-watchlist'
      path: '/create-watchlist'
      fullPath: '/create-watchlist'
      preLoaderRoute: typeof CreateWatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$ticker': {
      id: '/asset/$ticker'
      path: '/asset/$ticker'
      fullPath: '/asset/$ticker'
      preLoaderRoute: typeof AssetTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  CreateWatchlistRoute: CreateWatchlistRoute,
  ListsRoute: ListsRoute,
  LoginRoute: LoginRoute,
  RankingsRoute: RankingsRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  AssetTickerRoute: AssetTickerRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
